const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_VIDEOGAME_DETAILS = 'GET_VIDEOGAME_DETAILS';
const GET_GENRES = 'GET_GENRES';
const ADD_VIDEOGAME = 'ADD_VIDEOGAME';

export {
    GET_GENRES,
    GET_VIDEOGAMES,
    GET_VIDEOGAME_DETAILS,
    ADD_VIDEOGAME
}