const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_VIDEOGAMES_NAME = 'GET_VIDEOGAMES_NAME';
const VIDEOGAME_FILTERED = 'VIDEOGAME_FILTERED';
const GET_GENRES = 'GET_GENRES';
const ADD_VIDEOGAME = 'ADD_VIDEOGAME';
const SORT = 'SORT';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const SET_ORDER = 'SET_ORDER'
const CLEAN_UP = 'CLEAN_UP'

export {
    GET_GENRES,
    GET_VIDEOGAMES_NAME,
    GET_VIDEOGAMES,
    VIDEOGAME_FILTERED,
    ADD_VIDEOGAME,
    SORT,
    SET_CURRENT_PAGE,
    SET_ORDER,
    CLEAN_UP
}