const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_VIDEOGAMES_NAME = 'GET_VIDEOGAMES_NAME';
const VIDEOGAME_FILTERED = 'VIDEOGAME_FILTERED';
const GET_GENRES = 'GET_GENRES';
const ADD_VIDEOGAME = 'ADD_VIDEOGAME';
const SORT = 'SORT'

export {
    GET_GENRES,
    GET_VIDEOGAMES_NAME,
    GET_VIDEOGAMES,
    VIDEOGAME_FILTERED,
    ADD_VIDEOGAME,
    SORT
}